export const GET_GEO_LOCATION = 'GET_GEO_LOCATION'
export const ERROR_GEO_LOCATION = 'ERROR_GEO_LOCATION'
export const ERROR_HEROKU_GEO_LOCATION = 'ERROR_HEROKU_GEO_LOCATION'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const ERROR_CUSTOMERS = 'ERROR_CUSTOMERS'

export const GET_SUPPLIERS = 'GET_SUPPLIERS'
export const ERROR_SUPPLIERS = 'ERROR_SUPPLIERS'

export const GET_NEARBY_SUPPLIERS = 'GET_NEARBY_SUPPLIERS'